### ISSUE TITLE
-create (xyz)

### ISSUE THREAD

**Issue by Moonib** [ElShroomster/TourneyBot#3]
Gives this error but still creates the team:
_Error:
Command raised an exception: Forbidden: 403 Forbidden (error code: 50013): Missing Permissions_

**intended: Return a sufficient "Team xyz was created" message**

**Comment by Moonib** [comment]
Gave different response but still an error:
Error:
Command raised an exception: PermissionError: [Errno 13] Permission denied: 'data/teams.json'

**Comment by OhB00** [comment]
First error caused by role order in discord, the bot's role must be higher than the `Tournament Player` role

**Comment by OhB00** [comment]
Other issue was a file handling problem, will be resolved with API
