### ISSUE TITLE
-leave

### ISSUE THREAD

**Issue by Moonib** [ElShroomster/TourneyBot#5]
doing only -leave returns
_Error:
Command raised an exception: KeyError: '_

**intended: should just leave the current team without requiring the team name**

**Comment by OhB00** [comment]
![image](https://github.com/ElShroomster/TourneyBot/assets/43827372/a189bf9c-3d72-4a63-81b5-58c4bd075bf3)
This is a limitation of the current data storage system.

Will fix after API implementation

O(n) 🤮
