### ISSUE TITLE
tourney logs/announcements

### ISSUE THREAD

**Issue by Moonib** [ElShroomster/TourneyBot#6]
only logs when a team is created that it joins the tournament, and when it is disbanded it does not say that it leaves.

**intended: when a team is disbanded show that the team has left the tournament**

**Comment by OhB00** [comment]
![image](https://github.com/ElShroomster/TourneyBot/assets/43827372/7017bd16-5795-48ff-90b9-a814a3772cc8)
Not desired ig?
